import { CheckCircleOutlined, EyeOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { App, Button, Card, List, Select, Space, Tag, Typography } from 'antd'
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../../api/client'

export function NotificationsPage() {
  const { message } = App.useApp(); const navigate = useNavigate(); const client = useQueryClient(); const [search] = useSearchParams(); const [unread, setUnread] = useState<boolean | undefined>(search.get('unread') === 'true' ? true : undefined); const [risk, setRisk] = useState<string>(); const [cursor, setCursor] = useState<string>()
  const query = useQuery({ queryKey: ['notifications', unread, risk, cursor], queryFn: () => api.listNotifications({ unread, risk_level: risk, cursor, limit: 30 }) })
  const refresh = () => { void client.invalidateQueries({ queryKey: ['notifications'] }); void client.invalidateQueries({ queryKey: ['notification-summary'] }); void client.invalidateQueries({ queryKey: ['admin-dashboard'] }) }
  const read = useMutation({ mutationFn: api.markNotificationRead, onSuccess: (item) => { refresh(); navigate(item.link) }, onError: (e: Error) => message.error(e.message) })
  const resolve = useMutation({ mutationFn: api.resolveNotification, onSuccess: () => { message.success('已确认处理'); refresh() }, onError: (e: Error) => message.error(e.message) })
  return <div className="page"><div className="page-heading"><div><div className="page-eyebrow">Risk inbox</div><Typography.Title level={2}>通知中心</Typography.Title><Typography.Paragraph type="secondary">汇总需要管理员关注的账号、资源与运行风险，处理状态由管理员团队共享。</Typography.Paragraph></div><Space><Select allowClear placeholder="全部状态" value={unread === undefined ? undefined : String(unread)} options={[{ value: 'true', label: '仅未读' }, { value: 'false', label: '已读' }]} onChange={(v) => { setCursor(undefined); setUnread(v === undefined ? undefined : v === 'true') }} /><Select allowClear placeholder="全部风险" value={risk} options={[{ value: 'high', label: '高风险' }, { value: 'normal', label: '关注' }]} onChange={(v) => { setCursor(undefined); setRisk(v) }} /></Space></div>
    <Card className="content-card"><List loading={query.isLoading} dataSource={query.data?.items ?? []} renderItem={(item) => <List.Item className={item.read ? '' : 'notification-unread'} actions={[<Button key="view" icon={<EyeOutlined />} onClick={() => read.mutate(item.id)}>查看</Button>, <Button key="resolve" type={item.resolved ? 'default' : 'primary'} disabled={item.resolved} icon={<CheckCircleOutlined />} onClick={() => resolve.mutate(item.id)}>{item.resolved ? '已处理' : '确认处理'}</Button>]}><List.Item.Meta title={<Space>{!item.read && <span className="unread-dot" />}<span>{item.title}</span><Tag color={item.risk_level === 'high' ? 'error' : 'warning'}>{item.risk_level === 'high' ? '高风险' : '关注'}</Tag>{item.resolved && <Tag color="success">已处理</Tag>}</Space>} description={<Space direction="vertical" size={2}><span>{item.message}</span><Typography.Text type="secondary">{new Date(item.created_at).toLocaleString('zh-CN')}{item.owner_username ? ` · 所属 ${item.owner_username}` : ''}</Typography.Text></Space>} /></List.Item>} /><div className="audit-load-more"><Button disabled={!query.data?.next_cursor} onClick={() => setCursor(query.data?.next_cursor)}>下一页</Button></div></Card>
  </div>
}
