import { DeleteOutlined, EyeOutlined, KeyOutlined, LogoutOutlined, PlusOutlined, SwapOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { App, Button, Card, Descriptions, Drawer, Form, Input, Modal, Select, Space, Statistic, Switch, Table, Tag, Typography } from 'antd'
import { useEffect, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../../api/client'
import { useAuth } from '../../app/AuthContext'
import type { Session, User } from '../../types'
import { mainTablePagination } from '../../components/ListPagination'

export function UsersPage() {
  const { message, modal } = App.useApp(); const auth = useAuth(); const client = useQueryClient(); const navigate = useNavigate(); const [search] = useSearchParams()
  const [createOpen, setCreateOpen] = useState(false); const [resetUser, setResetUser] = useState<User | null>(null); const [detailID, setDetailID] = useState<string>(); const [transferOpen, setTransferOpen] = useState(false)
  const [form] = Form.useForm(); const [resetForm] = Form.useForm(); const [transferForm] = Form.useForm()
  useEffect(() => { const id = search.get('user_id'); if (id) setDetailID(id) }, [search])
  const users = useQuery({ queryKey: ['users'], queryFn: api.listUsers })
  const detail = useQuery({ queryKey: ['user-detail', detailID], queryFn: () => api.getUserDetail(detailID!), enabled: Boolean(detailID) })
  const sessions = useQuery({ queryKey: ['user-sessions', detailID], queryFn: () => api.listUserSessions(detailID!), enabled: Boolean(detailID) })
  const refresh = () => { void client.invalidateQueries({ queryKey: ['users'] }); void client.invalidateQueries({ queryKey: ['user-detail'] }); void client.invalidateQueries({ queryKey: ['admin-dashboard'] }) }
  const create = useMutation({ mutationFn: api.createUser, onSuccess: () => { message.success('账号已创建，首次登录必须修改密码'); setCreateOpen(false); form.resetFields(); refresh() }, onError: (e: Error) => message.error(e.message) })
  const status = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => api.updateUserStatus(id, enabled), onSuccess: refresh, onError: (e: Error) => message.error(e.message) })
  const reset = useMutation({ mutationFn: ({ id, password, requireChange }: { id: string; password: string; requireChange: boolean }) => api.resetUserPassword(id, password, requireChange), onSuccess: () => { message.success('密码已重置，账号会话已撤销'); setResetUser(null); resetForm.resetFields(); refresh() }, onError: (e: Error) => message.error(e.message) })
  const remove = useMutation({ mutationFn: api.deleteUser, onSuccess: () => { message.success('账号已删除'); setDetailID(undefined); refresh() }, onError: (e: Error) => message.error(e.message) })
  const revoke = useMutation({ mutationFn: api.revokeUserSessions, onSuccess: () => { message.success('账号已强制下线'); refresh() }, onError: (e: Error) => message.error(e.message) })
  const revokeSession = useMutation({ mutationFn: ({ userID, sessionID }: { userID: string; sessionID: string }) => api.revokeUserSession(userID, sessionID), onSuccess: () => { message.success('指定会话已撤销'); void sessions.refetch(); refresh() }, onError: (e: Error) => message.error(e.message) })
  const transfer = useMutation({ mutationFn: ({ id, target }: { id: string; target: string }) => api.transferUserResources(id, target), onSuccess: (result) => { message.success(`交接完成：${result.packages} 个安装包、${result.environments} 个环境、${result.models} 个模型`); setTransferOpen(false); transferForm.resetFields(); refresh(); void client.invalidateQueries() }, onError: (e: Error) => message.error(e.message) })
  const selected = detail.data
  return <div className="page">
    <div className="page-heading"><div><div className="page-eyebrow">Access control</div><Typography.Title level={2}>账号管理</Typography.Title><Typography.Paragraph type="secondary">管理账号生命周期、有效会话和业务资源交接。</Typography.Paragraph></div><Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateOpen(true)}>新增账号</Button></div>
    <Card className="content-card table-card" styles={{ body: { padding: 0 } }}><Table rowKey="id" dataSource={users.data ?? []} loading={users.isLoading} pagination={mainTablePagination} tableLayout="fixed" scroll={{ x: 1040 }} columns={[
      { title: '用户名', dataIndex: 'username', width: 240, render: (v: string, u: User) => <div className="table-inline-cell"><Typography.Text strong ellipsis={{ tooltip: v }}>{v}</Typography.Text>{u.is_initial_admin && <Tag color="gold">初始管理员</Tag>}</div> },
      { title: '角色', dataIndex: 'role', width: 110, render: (v: string) => <Tag color={v === 'admin' ? 'blue' : 'default'}>{v === 'admin' ? '管理员' : '普通账号'}</Tag> },
      { title: '状态', width: 140, render: (_: unknown, u: User) => <Switch checked={u.enabled} disabled={u.is_initial_admin || u.id === auth.user.id} onChange={(enabled) => status.mutate({ id: u.id, enabled })} checkedChildren="启用" unCheckedChildren="禁用" /> },
      { title: '创建时间', dataIndex: 'created_at', width: 190, render: (v: string) => new Date(v).toLocaleString('zh-CN') },
      { title: '操作', width: 360, fixed: 'right', render: (_: unknown, u: User) => <div className="row-actions"><Button icon={<EyeOutlined />} onClick={() => setDetailID(u.id)}>详情</Button><Button icon={<KeyOutlined />} onClick={() => { resetForm.setFieldsValue({ password: '', requireChange: true }); setResetUser(u) }}>重置密码</Button><Button danger icon={<DeleteOutlined />} disabled={u.is_initial_admin || u.id === auth.user.id} onClick={() => modal.confirm({ title: `删除账号 ${u.username}？`, content: '仅无业务资源的账号可以删除。', okButtonProps: { danger: true }, onOk: () => remove.mutate(u.id) })}>删除</Button></div> },
    ]} /></Card>
    <Drawer width={620} title={selected ? `账号详情 · ${selected.username}` : '账号详情'} open={Boolean(detailID)} onClose={() => setDetailID(undefined)} loading={detail.isLoading} extra={selected && <Space><Button icon={<LogoutOutlined />} disabled={selected.id === auth.user.id} onClick={() => modal.confirm({ title: `强制下线 ${selected.username}？`, content: '该账号的全部有效会话将立即失效。', onOk: () => revoke.mutate(selected.id) })}>强制下线</Button><Button type="primary" icon={<SwapOutlined />} disabled={selected.package_count + selected.environment_count === 0} onClick={() => setTransferOpen(true)}>资源交接</Button></Space>}>
      {selected && <><Descriptions column={2} bordered size="small" items={[{ key: 'role', label: '角色', children: selected.role === 'admin' ? '管理员' : '普通账号' }, { key: 'status', label: '状态', children: selected.enabled ? '启用' : '禁用' }, { key: 'password', label: '密码状态', children: selected.must_change_password ? <Tag color="orange">待首次改密</Tag> : '正常' }, { key: 'creator', label: '创建人', children: selected.created_by_username || '系统初始化' }, { key: 'created', label: '创建时间', children: new Date(selected.created_at).toLocaleString('zh-CN') }, { key: 'login', label: '最近登录', children: selected.last_login_at ? new Date(selected.last_login_at).toLocaleString('zh-CN') : '从未登录' }, { key: 'ip', label: '最近来源 IP', children: selected.last_source_ip || '-' }, { key: 'activity', label: '最近活动', children: selected.last_activity_at ? new Date(selected.last_activity_at).toLocaleString('zh-CN') : '-' }, { key: 'sessions', label: '有效会话', children: selected.active_session_count }]} /><div className="user-stat-grid"><Statistic title="安装包" value={selected.package_count} /><Statistic title="环境" value={selected.environment_count} /><Statistic title="已安装服务" value={selected.installed_service_count} /><Statistic title="近 30 天操作" value={selected.recent_operation_count} /><Statistic title="登录失败" value={selected.login_failure_count} /><Statistic title="高风险事件" value={selected.high_risk_count} /></div><Typography.Title level={5}>有效会话</Typography.Title><Table<Session> rowKey="id" size="small" pagination={false} scroll={{ x: 850 }} loading={sessions.isLoading} dataSource={sessions.data ?? []} columns={[{ title: '客户端', dataIndex: 'user_agent', width: 180, ellipsis: true, render: (v: string) => v || '未知客户端' }, { title: '来源 IP', dataIndex: 'source_ip', width: 120, render: (v: string) => v || '-' }, { title: '登录时间', dataIndex: 'created_at', width: 160, render: (v: string) => new Date(v).toLocaleString('zh-CN') }, { title: '最近活动', dataIndex: 'last_seen_at', width: 160, render: (v: string) => new Date(v).toLocaleString('zh-CN') }, { title: '过期时间', dataIndex: 'expires_at', width: 160, render: (v: string) => new Date(v).toLocaleString('zh-CN') }, { title: '操作', width: 80, fixed: 'right', render: (_: unknown, item) => <Button danger size="small" disabled={item.current} onClick={() => revokeSession.mutate({ userID: selected.id, sessionID: item.id })}>{item.current ? '当前会话' : '撤销'}</Button> }]} /><Space wrap style={{ marginTop: 18 }}><Button onClick={() => navigate(`/packages?owner_id=${selected.id}`)}>查看安装包</Button><Button onClick={() => navigate(`/environments?owner_id=${selected.id}`)}>查看环境</Button><Button onClick={() => navigate(`/services?owner_id=${selected.id}`)}>查看服务</Button><Button onClick={() => navigate(`/audit?owner_id=${selected.id}`)}>查看审计</Button></Space><Typography.Paragraph type="secondary" style={{ marginTop: 18 }}>建议离职流程：先禁用并强制下线，再完成资源交接，确认资源清零后删除账号。</Typography.Paragraph></>}
    </Drawer>
    <Modal title="新增账号" open={createOpen} onCancel={() => setCreateOpen(false)} onOk={() => form.validateFields().then((v) => create.mutate(v))} confirmLoading={create.isPending}><Form form={form} layout="vertical" initialValues={{ role: 'user' }}><Form.Item name="username" label="用户名" rules={[{ required: true }, { pattern: /^[a-z0-9][a-z0-9._-]{2,31}$/, message: '3–32 位小写字母、数字、点、下划线或连字符' }]}><Input /></Form.Item><Form.Item name="password" label="初始密码" extra="该密码仅用于首次登录，账号登录后必须自行修改。" rules={[{ required: true }, { min: 8, max: 128 }]}><Input.Password /></Form.Item><Form.Item name="role" label="角色"><Select options={[{ value: 'user', label: '普通账号' }, { value: 'admin', label: '管理员' }]} /></Form.Item></Form></Modal>
    <Modal title={`重置密码${resetUser ? ` · ${resetUser.username}` : ''}`} open={Boolean(resetUser)} onCancel={() => { setResetUser(null); resetForm.resetFields() }} onOk={() => resetForm.validateFields().then(({ password, requireChange }) => reset.mutate({ id: resetUser!.id, password, requireChange }))} confirmLoading={reset.isPending}><Form form={resetForm} layout="vertical" initialValues={{ requireChange: true }}><Form.Item name="password" label="新密码" extra="重置成功后该账号全部会话立即失效" rules={[{ required: true }, { min: 8, max: 128 }]}><Input.Password /></Form.Item><Form.Item name="requireChange" label="下次登录必须修改密码" valuePropName="checked"><Switch checkedChildren="开启" unCheckedChildren="关闭" /></Form.Item><Typography.Paragraph type="secondary">开启后，账号使用临时密码登录时只能完成密码修改或退出。</Typography.Paragraph></Form></Modal>
    <Modal title={`资源交接 · ${selected?.username ?? ''}`} open={transferOpen} onCancel={() => setTransferOpen(false)} okText="确认交接" confirmLoading={transfer.isPending} onOk={() => transferForm.validateFields().then(({ target }) => transfer.mutate({ id: selected!.id, target }))}><Typography.Paragraph>将全部安装包、环境和服务配置转移给目标账号。存在运行中操作或唯一键冲突时整批拒绝，不会覆盖目标数据。</Typography.Paragraph><Form form={transferForm} layout="vertical"><Form.Item name="target" label="目标账号" rules={[{ required: true }]}><Select options={(users.data ?? []).filter((u) => u.enabled && u.id !== selected?.id).map((u) => ({ value: u.id, label: u.username }))} /></Form.Item></Form></Modal>
  </div>
}
